services:
  cm:
    build:
      context: ./docker/build/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cm:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}sitecore-spe-assets:${SPE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
    image: ${COMPOSE_PROJECT_NAME}-cm:${VERSION:-latest}
    volumes:
      - "${LOCAL_DEPLOY_PATH}/website:C:/deploy"
      - "${LOCAL_DATA_PATH}/cm:C:/inetpub/wwwroot/App_Data/logs"
      - "./docker/data/device-detection-data:C:/inetpub/wwwroot/App_Data/DeviceDetection"
    environment:
      SITECORE_DEVELOPMENT_PATCHES: CustomErrorsOff 
    entrypoint: powershell -Command "& C:\\tools\\entrypoints\\iis\\Development.ps1"
