---
ID: "031b6fef-1524-4183-812b-7ca57edc537f"
Parent: "34644cdc-1ca4-4550-b90a-46153e828143"
Template: "13d5af2a-ab19-4966-9afb-518e6cc09344"
Path: /sitecore/templates/Branches/Project/Banner/Banner/$name/LinkCollection
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240801T210049Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
