---
ID: "43b3ac73-7a53-4574-9674-30f3d9d18642"
Parent: "da04b275-8838-4a3a-afee-817cf1fdd2eb"
Template: "93227c5d-4fef-474d-94c0-f252ec8e8219"
Path: /sitecore/layout/Layouts/Project/Example
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240602T003124Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
