---
ID: "4a43f40c-0b17-4090-9c83-2896719a910a"
Parent: "cbb00edd-eddb-4e1b-98bc-c7060b6a2416"
Template: "5c547d4e-7111-4995-95b0-6b561751bf2e"
Path: /sitecore/layout/Placeholder Settings/Project/Example/ButtonContainer
DB: master
SharedFields:
- ID: "7256bdab-1fd2-49dd-b205-cb4873d2917c"
  Hint: Placeholder Key
  Value: button_container
- ID: "e391b526-d0c5-439d-803e-17512eae6222"
  Hint: Allowed Controls
  Type: TreelistEx
  Value: "{88A964EB-26A4-45D7-B067-338E99956684}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240803T033945Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
