---
ID: "ee69a808-d4bb-4457-b8b1-f90cb987fad8"
Parent: "ae54fdbd-806f-4e46-8c6e-7d500f7c0037"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Project/Example/HomePageTemplate/Page Information
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240602T003249Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
