---
ID: "84040039-9244-4e56-aee4-1adb61e2aa76"
Parent: "390785c2-4f3d-4c77-9ee2-aa130aecd639"
Template: "af21ddb6-5778-414e-b7b0-587e00c27ce6"
Path: /sitecore/content/Example/Home/Components
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240603T185019Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
