---
ID: "b2fc0921-d3ac-4070-9059-a49ee074ffef"
Parent: "ffc22ab5-2975-4d10-8ae0-09e774e69eb4"
Template: "ffc22ab5-2975-4d10-8ae0-09e774e69eb4"
Path: /sitecore/templates/Project/Example/Parameters/BannerParameter/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240802T025225Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
