---
ID: "1b77b76f-c12d-4bd2-be76-22e63da3a06a"
Parent: "ffc22ab5-2975-4d10-8ae0-09e774e69eb4"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Project/Example/Parameters/BannerParameter/Information
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240802T023901Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
